/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'totalAmount' : bigint,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'color' : string,
  'size' : string,
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : string,
  'featured' : boolean,
  'inStock' : boolean,
  'originalPrice' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'sizes' : Array<string>,
  'category' : ProductCategory,
  'rating' : number,
  'colors' : Array<string>,
  'price' : bigint,
  'reviewCount' : bigint,
  'images' : Array<string>,
}
export type ProductCategory = { 'Men' : null } |
  { 'Accessories' : null } |
  { 'Kids' : null } |
  { 'Women' : null };
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addToWishlist' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [Array<OrderItem>, ShippingAddress, bigint],
    { 'ok' : Order } |
      { 'err' : string }
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getOrderById' : ActorMethod<[string], [] | [Order]>,
  'getOrdersByUser' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getWishlist' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromWishlist' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedProducts' : ActorMethod<[], boolean>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [string, OrderStatus],
    { 'ok' : Order } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];